### ISSUE TITLE
what are emmie-tokens?

### ISSUE THREAD

**Issue by lazzarello** [upmc-enterprises/emmie#18]
in the RC spec there is an argument to be passed to the container like so

```
- -path-to-tokens=/etc/emmie-tokens/tokens.txt
```

what is the intended contents of this file? I see further down your demo places them in a k8s volume named tokens and mounts at `/etc/emmie-tokens`

**Comment by stevesloka** [comment]
Tokens are a cheap way to secure Emmie. Since typically I'm deploying Emmie to the public internet, I wanted a way to secure the API. This is done with some simple tokens over TLS. You can choose to not use them and if the token file is blank, tokens won't be enforced.

**Comment by lazzarello** [comment]
Okay cool. I'm using NodePort for now. Good to know your security model.
