### ISSUE TITLE
What is Traefik? Why do I need it?

### ISSUE THREAD

**Issue by lazzarello** [upmc-enterprises/emmie#20]
This dependency seems important but it is not well understood in the pipeline. How is this different than a k8s NodePort? Can I "just use a NodePort" if I don't want to set up a load balancer?

**Comment by stevesloka** [comment]
When a feature branch is created, we need a way to expose it so we can access. You can use NodePorts to accomplish this, but after deploying you have to query k8s to find out the node port for that specific branch. 

Alternatively, Emmie will read and update an Ingress route which allows for feature branches to be deployed via custom DNS names. I setup a wildcard dns entry (e..g *.ci.company.com), then emmie can setup an ingress route for each feature branch giving you: feature.ci.company.com or feature22.ci.company.com. 

It also saves you on load balancer costs (if deploying out to a cloud), but only having one (the ingress controller). You can read more about Ingress here: http://kubernetes.io/docs/user-guide/ingress/

Also, I'm using traefik as the ingress controller for no particular reason (other than I wanted to play with it).

**Comment by lazzarello** [comment]
fair enough. This is a cool feature and I like the project's background image  :)

My use case is for a more private configuration. I'm okay with the extra moving parts required to query the cluster and work with the NodePort type.
